// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCoreSeed.SampleRestaurant.Infrastructure.Context;

#nullable disable

namespace WebApiCoreSeed.SampleRestaurant.Infrastructure.Migrations
{
    [DbContext(typeof(SampleRestaurantDbContext))]
    partial class SampleRestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.Atendente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoAtendente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Atendentes", (string)null);
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.LogginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Escopo")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(6000)");

                    b.HasKey("Id");

                    b.ToTable("Loggin", (string)null);
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LocalizacaoMesa")
                        .HasColumnType("int");

                    b.Property<int>("Lugares")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Mesas", (string)null);
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtendenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DataHoraEncerrado")
                        .HasColumnType("datetime");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AtendenteId");

                    b.HasIndex("MesaId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.PedidoPrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusProducao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PratoId");

                    b.ToTable("PedidoPrato", (string)null);
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.Prato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(800)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<int>("TipoPrato")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Titulo", "Id");

                    b.ToTable("Pratos", (string)null);
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.Pedido", b =>
                {
                    b.HasOne("WebApiCoreSeed.SampleRestaurant.Models.Atendente", "Atendente")
                        .WithMany("Pedidos")
                        .HasForeignKey("AtendenteId")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Atendentes");

                    b.HasOne("WebApiCoreSeed.SampleRestaurant.Models.Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("MesaId")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Mesas");

                    b.Navigation("Atendente");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.PedidoPrato", b =>
                {
                    b.HasOne("WebApiCoreSeed.SampleRestaurant.Models.Pedido", "Pedido")
                        .WithMany("PedidoPrato")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK_PedidoPrato_Pedidos");

                    b.HasOne("WebApiCoreSeed.SampleRestaurant.Models.Prato", "Prato")
                        .WithMany("PedidoPrato")
                        .HasForeignKey("PratoId")
                        .IsRequired()
                        .HasConstraintName("FK_PedidoPrato_Pratos");

                    b.Navigation("Pedido");

                    b.Navigation("Prato");
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.Atendente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.Pedido", b =>
                {
                    b.Navigation("PedidoPrato");
                });

            modelBuilder.Entity("WebApiCoreSeed.SampleRestaurant.Models.Prato", b =>
                {
                    b.Navigation("PedidoPrato");
                });
#pragma warning restore 612, 618
        }
    }
}
